version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=host.docker.internal
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=profesores_db
      - DB_PORT=3306
    
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend  # El frontend depende del backend, pero no al revés.
